# This is a basic workflow to help you get started with Actions

name: FilmTalk

on:
  push:
    branches: [ "Develop" ]
  pull_request:
    branches: [ "Develop" ]

  workflow_dispatch:

jobs:

  build:
  
    runs-on: ubuntu-latest
  
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.11
        uses: actions/setup-python@v3
        with:
          python-version: "3.11"
      - name: Install dependencies
        run: |
            python -m pip install --upgrade pip
            if [ -f requirements.txt ]; them pip install -r requirements.txt;
      - name: Test with pytest
        run: |
            pytest
